package com.vyaapaar.dao;

import com.vyaapaar.config.PostgreSQLConnection;
import com.vyaapaar.model.report.CategoryRevenueReport;
import com.vyaapaar.model.report.CustomerAnalysisReport;
import com.vyaapaar.model.report.CustomerSpendingReport;
import com.vyaapaar.model.report.MonthlySalesReport;
import com.vyaapaar.model.report.ProductSalesReport;
import com.vyaapaar.model.report.SalesSummaryReport;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object for PostgreSQL Advanced Reporting & Analytics Queries.
 * Demonstrates: JOINs, GROUP BY, HAVING, Subqueries, Aggregate functions, CASE, and Date functions.
 */
public class ReportingDao {

    /**
     * Report A-D, J: High-level sales summary.
     * Demonstrates: Scalar Subqueries, Aggregate functions (COUNT, SUM, AVG), COALESCE, and WHERE filtering.
     */
    public SalesSummaryReport getSalesSummary() {
        String sql = "SELECT " +
                     "  (SELECT COUNT(*) FROM report_users) AS total_customers, " +
                     "  (SELECT COUNT(*) FROM report_products) AS total_products, " +
                     "  COUNT(order_id) AS total_orders, " +
                     "  COALESCE(SUM(total_amount), 0) AS total_revenue, " +
                     "  COALESCE(AVG(total_amount), 0) AS avg_order_value " +
                     "FROM report_orders " +
                     "WHERE order_status != 'CANCELLED'";

        try (Connection conn = PostgreSQLConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                return new SalesSummaryReport(
                        rs.getInt("total_customers"),
                        rs.getInt("total_products"),
                        rs.getInt("total_orders"),
                        rs.getDouble("total_revenue"),
                        rs.getDouble("avg_order_value")
                );
            }
        } catch (SQLException e) {
            System.err.println("PostgreSQL Error [getSalesSummary]: " + e.getMessage());
        }
        return null;
    }

    /**
     * Report E: Total revenue generated by each product category.
     * Demonstrates: Multi-table INNER JOIN, GROUP BY, Aggregate SUM(), and ORDER BY DESC.
     */
    public List<CategoryRevenueReport> getRevenueByCategory() {
        List<CategoryRevenueReport> list = new ArrayList<>();
        String sql = "SELECT " +
                     "  c.category_name, " +
                     "  COALESCE(SUM(oi.subtotal), 0) AS total_revenue, " +
                     "  COALESCE(SUM(oi.quantity), 0) AS total_qty " +
                     "FROM report_categories c " +
                     "INNER JOIN report_products p ON c.category_id = p.category_id " +
                     "INNER JOIN report_order_items oi ON p.product_id = oi.product_id " +
                     "INNER JOIN report_orders o ON oi.order_id = o.order_id " +
                     "WHERE o.order_status != 'CANCELLED' " +
                     "GROUP BY c.category_id, c.category_name " +
                     "ORDER BY total_revenue DESC";

        try (Connection conn = PostgreSQLConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                list.add(new CategoryRevenueReport(
                        rs.getString("category_name"),
                        rs.getDouble("total_revenue"),
                        rs.getInt("total_qty")
                ));
            }
        } catch (SQLException e) {
            System.err.println("PostgreSQL Error [getRevenueByCategory]: " + e.getMessage());
        }
        return list;
    }

    /**
     * Report F: Top-selling products ordered by quantity sold and revenue generated.
     * Demonstrates: Multi-table INNER JOIN, GROUP BY with multiple dimensions, and multi-column ORDER BY.
     */
    public List<ProductSalesReport> getTopSellingProducts() {
        List<ProductSalesReport> list = new ArrayList<>();
        String sql = "SELECT " +
                     "  p.name AS product_name, " +
                     "  c.category_name, " +
                     "  SUM(oi.quantity) AS total_quantity, " +
                     "  SUM(oi.subtotal) AS total_revenue " +
                     "FROM report_products p " +
                     "INNER JOIN report_categories c ON p.category_id = c.category_id " +
                     "INNER JOIN report_order_items oi ON p.product_id = oi.product_id " +
                     "INNER JOIN report_orders o ON oi.order_id = o.order_id " +
                     "WHERE o.order_status != 'CANCELLED' " +
                     "GROUP BY p.product_id, p.name, c.category_name " +
                     "ORDER BY total_quantity DESC, total_revenue DESC";

        try (Connection conn = PostgreSQLConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                list.add(new ProductSalesReport(
                        rs.getString("product_name"),
                        rs.getString("category_name"),
                        rs.getInt("total_quantity"),
                        rs.getDouble("total_revenue")
                ));
            }
        } catch (SQLException e) {
            System.err.println("PostgreSQL Error [getTopSellingProducts]: " + e.getMessage());
        }
        return list;
    }

    /**
     * Report G: Top customers ranked by cumulative spending.
     * Demonstrates: INNER JOIN, GROUP BY, HAVING clause, and Aggregate functions (COUNT, SUM, AVG).
     */
    public List<CustomerSpendingReport> getTopCustomers() {
        List<CustomerSpendingReport> list = new ArrayList<>();
        String sql = "SELECT " +
                     "  u.user_id, " +
                     "  u.full_name, " +
                     "  u.email, " +
                     "  COUNT(o.order_id) AS order_count, " +
                     "  SUM(o.total_amount) AS total_spent, " +
                     "  AVG(o.total_amount) AS avg_order_value " +
                     "FROM report_users u " +
                     "INNER JOIN report_orders o ON u.user_id = o.user_id " +
                     "WHERE o.order_status != 'CANCELLED' " +
                     "GROUP BY u.user_id, u.full_name, u.email " +
                     "HAVING COUNT(o.order_id) > 0 " +
                     "ORDER BY total_spent DESC";

        try (Connection conn = PostgreSQLConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                list.add(new CustomerSpendingReport(
                        rs.getInt("user_id"),
                        rs.getString("full_name"),
                        rs.getString("email"),
                        rs.getInt("order_count"),
                        rs.getDouble("total_spent"),
                        rs.getDouble("avg_order_value")
                ));
            }
        } catch (SQLException e) {
            System.err.println("PostgreSQL Error [getTopCustomers]: " + e.getMessage());
        }
        return list;
    }

    /**
     * Report K: Monthly revenue and order volume trend.
     * Demonstrates: Date formatting and chronological grouping with TO_CHAR(), COUNT(), SUM(), MIN(), MAX().
     */
    public List<MonthlySalesReport> getMonthlySales() {
        List<MonthlySalesReport> list = new ArrayList<>();
        String sql = "SELECT " +
                     "  TO_CHAR(order_date, 'YYYY-MM') AS sales_month, " +
                     "  COUNT(order_id) AS order_count, " +
                     "  SUM(total_amount) AS total_revenue " +
                     "FROM report_orders " +
                     "WHERE order_status != 'CANCELLED' " +
                     "GROUP BY TO_CHAR(order_date, 'YYYY-MM') " +
                     "ORDER BY sales_month ASC";

        try (Connection conn = PostgreSQLConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                list.add(new MonthlySalesReport(
                        rs.getString("sales_month"),
                        rs.getInt("order_count"),
                        rs.getDouble("total_revenue")
                ));
            }
        } catch (SQLException e) {
            System.err.println("PostgreSQL Error [getMonthlySales]: " + e.getMessage());
        }
        return list;
    }

    /**
     * Report M: Detailed purchase analysis for a single customer.
     * Demonstrates: Parameterized WHERE, LEFT JOIN, CASE expression, and Aggregate MAX() / AVG().
     */
    public CustomerAnalysisReport getCustomerPurchaseAnalysis(int customerId) {
        String sql = "SELECT " +
                     "  u.user_id, " +
                     "  u.full_name, " +
                     "  u.email, " +
                     "  u.city, " +
                     "  COUNT(o.order_id) AS order_count, " +
                     "  COALESCE(SUM(CASE WHEN o.order_status != 'CANCELLED' THEN o.total_amount ELSE 0 END), 0) AS total_spent, " +
                     "  COALESCE(AVG(CASE WHEN o.order_status != 'CANCELLED' THEN o.total_amount ELSE NULL END), 0) AS avg_order_value, " +
                     "  MAX(o.order_date) AS last_order_date " +
                     "FROM report_users u " +
                     "LEFT JOIN report_orders o ON u.user_id = o.user_id " +
                     "WHERE u.user_id = ? " +
                     "GROUP BY u.user_id, u.full_name, u.email, u.city";

        try (Connection conn = PostgreSQLConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, customerId);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return new CustomerAnalysisReport(
                            rs.getInt("user_id"),
                            rs.getString("full_name"),
                            rs.getString("email"),
                            rs.getString("city"),
                            rs.getInt("order_count"),
                            rs.getDouble("total_spent"),
                            rs.getDouble("avg_order_value"),
                            rs.getTimestamp("last_order_date")
                    );
                }
            }
        } catch (SQLException e) {
            System.err.println("PostgreSQL Error [getCustomerPurchaseAnalysis]: " + e.getMessage());
        }
        return null;
    }

    /**
     * Report I: Inactive customers who have never placed an order.
     * Demonstrates: Subquery with NOT IN (SELECT DISTINCT ...).
     */
    public List<String> getInactiveCustomers() {
        List<String> list = new ArrayList<>();
        String sql = "SELECT u.user_id, u.full_name, u.email " +
                     "FROM report_users u " +
                     "WHERE u.user_id NOT IN (SELECT DISTINCT user_id FROM report_orders)";

        try (Connection conn = PostgreSQLConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                list.add(String.format("[%d] %s (%s)", rs.getInt("user_id"), rs.getString("full_name"), rs.getString("email")));
            }
        } catch (SQLException e) {
            System.err.println("PostgreSQL Error [getInactiveCustomers]: " + e.getMessage());
        }
        return list;
    }
}
